### ISSUE TITLE
Server

### ISSUE THREAD

**Issue by Stephan18** [corristo/xmlrpc#14]
Hi,

Thanks for this library. Very nice.
But i have an Question.. 

I need to start an Server on iOS. As example, in node.js it works like this:
<pre>        var rpcServer = rpc.createServer({
                host: "192.168.178.76",
                port: "8086"
        });
        console.log("Server started");
        sendInit();

       rpcServer.on('NotFound', function (method, params) {
                console.log("Notfound: " + method + " und " + params);
        });

        rpcServer.on('system.multicall', function (method, params, callback) {</pre>

Is it posible, to Start an Server on iOS? 
If yes, can you say me what to do please?

One more example:
on node.js i send this request:
<pre>       rpcClient.methodCall('init', ["http://192.168.178.76:8086", "server"], function (err, data) {</pre>

After this call, i am in an queue for notifications. The other side sends now to this IP Adress xml notifications.

My goal:
1.) On iOS, start an xml Server, to response xml-data from server
2.) On iOS send request to server in local network like this:
<pre>       rpcClient.methodCall('init', ["http://192.168.178.76:8086", "server"], function (err, data) {</pre>
3.) the local Server sends now xml-data to 192.168.178.72

<b>In this example, <u>192.168.178.76</u> is my iPhone! Step 3 already works. My local Server sends xml-data. But my iPhone doesn't understand this ;-)</b>

The iOS Server have to run all time, if App is running. I think AppDelegate.m has to extend.

Sorry for my bad Englisch.

Greetings from Germany.

**Comment by corristo** [comment]
Hi,

unfortunately this library doesn't provide a server that could be run on iOS.
