### ISSUE TITLE
Searching records, no idea how to write code?

### ISSUE THREAD

**Issue by ericmachine88** [corristo/xmlrpc#9]
Hi there,

I have difficulty writing codes using your library. Need help.

I need to use objective-c (ios 7 app) to talk to openerp. 

https://doc.odoo.com/6.0/developer/6_22_XML-RPC_web_services/

I have used cocoapads to install your library without any problems.

But I couldn't figure out what's wrong? 

questions:-

a) How should I construct my code?

i. login first
ii. search for a partner
iii. get the partner details and assigned to a label

which methods, events should I use?

b) I am getting a lot of openerp errors. But I am not sure whether you could assist. But I wonder you could advise how should I construct the code so I could test further.

My code as below:-

ViewController.h

```
#import <UIKit/UIKit.h>
#import "XMLRPC.h"

@interface ViewController : UIViewController <XMLRPCConnectionDelegate>

- (IBAction)callXMLRPC:(id)sender;

@end
```

ViewController.m

```
#import "ViewController.h"

@interface ViewController ()

@end

@implementation ViewController

- (void)viewDidLoad
{
    [super viewDidLoad];
	// Do any additional setup after loading the view, typically from a nib.
}

- (void)didReceiveMemoryWarning
{
    [super didReceiveMemoryWarning];
    // Dispose of any resources that can be recreated.
}

- (IBAction)callXMLRPC:(id)sender {
    NSString *user = @"admin";
    NSString *pwd = @"admin";
    NSString *dbname = @"awesome";
    
    // login first
    
    NSURL *URL = [NSURL URLWithString:@"http://10.3.8.162:8069/xmlrpc/common"];
    XMLRPCRequest *request = [[XMLRPCRequest alloc] initWithURL:URL];
    XMLRPCConnectionManager *manager = [XMLRPCConnectionManager sharedManager];
    NSArray *openerpParams = [[NSArray alloc] initWithObjects:dbname, user, pwd, nil];
    [request setMethod:@"login" withParameters:openerpParams];
    //NSLog(@"Request body: %@", [request body]);
    [manager spawnConnectionWithXMLRPCRequest:request delegate:self];
    
    // search partner, I am not sure whether I should search here ???
    URL = [NSURL URLWithString:@"http://10.3.8.162:8069/xmlrpc/object"];
    
    NSString *model = @"res.partner";
    NSString *arg = @"name=superman";
    
    request = [[XMLRPCRequest alloc] initWithURL:URL];

    openerpParams = [[NSArray alloc] initWithObjects:dbname, user, pwd, model, arg, nil];
  
    [request setMethod:@"execute" withParameters:openerpParams];

    [manager spawnConnectionWithXMLRPCRequest:request delegate:self];
    
}

- (void)request:(XMLRPCRequest *)request didReceiveResponse:(XMLRPCResponse *)response {
   // Do I get back the partner's data here? I need to get back "name", "phone", "email"
    NSLog(@"Response body: %@", [response body]);
}

@end
```
Any help? Thanks.

**Comment by chriskikoti** [comment]
Hi, I have two questions I need help:
1. I need to retrieve specific node of the returned xml and I don't know how to do it.
2. I need to send xmlrpc object with <struct> but now it doesn't include the <struct> node. Thanks!

**Comment by corristo** [comment]
@chriskikoti both questions have nothing to do will xmlrpc itself, it's just a matter of using Cocoa collections.

I'll assume that your response is `NSArray` or `NSDictionary`

1. It seems that you have to iterate over all nodes in your response and find one with your specific criteria.
2. Try to make mutable copy of response, and remove unnecessary node, then send it as a request.

**Comment by chriskikoti** [comment]
Thanks @corristo  for the enlightenment, I have changed the request params from NSArray to NSDictionary and worked fine for part 2. of my question. Now I am working on part 1 of it. Thanks!
